### PR TITLE
NLRFIM-130 - Store query parameters in session when redirecting to IdP

### PR DESCRIPTION
**Pull request by TauBeblein**
This implementation is the one suggested in the incident, but this could also be solved by setting responseLocation on the  SingleSignOnService endpoint on the auth request...

### CODE REVIEW

**Review by mdbech — CHANGES_REQUESTED** [review]
Please update the RELEASE_NOTES.md-file as well. Otherwise approved.

**Comment by TauBeblein** [comment]
Done, bumping POM version as well, to reflect the current version

**Comment by mdbech** [comment]
> Done, bumping POM version as well, to reflect the current version

Don't you also need to update the child POMs references to the parent version?

**Comment by TauBeblein** [comment]
done

**Review by mdbech — APPROVED** [review]

**Pull request merged**
